version: '3'
volumes:
  dados:
services:
    db:
        image: postgres:9.6 
        volumes:
            #Volume dos dados
            - dados:/var/lib/postgresql/data
            #Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql  # inicializa a estrtura do bco ddos
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
    frontend:
        image: nginx:1.13
        volumes:
             # Site
             - ./web:/usr/share/nginx/html/
        ports:
            - 80:80
    app: python:3.6
        volumes: 
            #aplicaçao
            - ./app:/app  #Local arquivo shell app.sh e sender.py
        working_dir: /app
        command: ./app.sh
        ports:
            -8080:8080